name: dreport
description: Parse and convert Dart analysis, test reports to other formats.
version: 0.0.1
repository: https://github.com/hawkkiller/dreport

environment:
  sdk: ^3.7.2

dependencies:
  args: ^2.5.0
  cli_util: ^0.4.2
  crypto: ^3.0.6
  xml: ^6.5.0

dev_dependencies:
  test: ^1.24.0
  sizzle_lints: ^2.1.7
